#!/bin/bash

i=0
for IP in $(arp -n | grep -v incomplete | grep -v Iface | awk '{print $1}' | sort -V )
do
	#echo -ne $IP '\t'
	if nmap -sn $IP | grep "is up" > /dev/null
	then
		#echo -n $IP 
		nome=$(timeout 1 nmblookup -A $IP | grep ACTIVE | head -1 |tr -d "\t" | tr -d " " | awk -F "<" '{print $1}')
		echo $IP "	" $nome
		i=$((i + 1))
	fi
		
done

echo $i "hosts up"

