#!/usr/bin/php
<?php
$command = "smbstatus -b | grep \"@\" | awk '{print $2 \"\t\" $5 \"\t\" $1}' | sort -h | uniq";
$listusers = shell_exec($command);
$listusers_array = explode("\n", chop($listusers));
foreach($listusers_array as $users){
	$users_tmp = explode("\t", $users);
	echo $users_tmp[0];
	$command="timeout 0.1 nmblookup -A " . $users_tmp[1] . " | grep \"<00>\" | head -1 | awk {'print $1'}";
	$hostname = shell_exec($command);
	echo $users_tmp[1] . "\n";
	if(isset($hostname)){ echo " - " . $hostname; }

	// thanks to @MrE for idea
	$command = "smbstatus -L | grep " . $users_tmp[2] . " | awk -F \"/var/lib/nethserver/\" {'print \"\t\" $2'} | sed 's/   /|/g' | awk -F \"|\" {'print \"\t\" $3 \" - \" $1 \"/\" $2'}";	
	$locked = shell_exec($command);
	echo $locked;

}
?>
